"""Upload Document Schema Update for Job Description

Revision ID: 07dee787ecf1
Revises: 1f5db8adfc82
Create Date: 2025-09-29 09:39:54.683266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dee787ecf1'
down_revision: Union[str, None] = '1f5db8adfc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('original_document_filename', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('original_document_size', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('original_document_extension', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('document_word_count', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('document_character_count', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'document_character_count')
    op.drop_column('job_descriptions', 'document_word_count')
    op.drop_column('job_descriptions', 'original_document_extension')
    op.drop_column('job_descriptions', 'original_document_size')
    op.drop_column('job_descriptions', 'original_document_filename')
    # ### end Alembic commands ###
