"""initial schema

Revision ID: 1f5db8adfc82
Revises: 
Create Date: 2025-09-26 14:41:44.069616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1f5db8adfc82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=False),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('cv_path', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('scores', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scores_persona_id'), 'scores', ['persona_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('refined_text', sa.Text(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('selected_version', sa.String(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('selected_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_description_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weights', sqlite.JSON(), nullable=True),
    sa.Column('intervals', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_job_description_id'), 'personas', ['job_description_id'], unique=False)
    op.create_table('persona_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_percentage', sa.Integer(), nullable=False),
    sa.CheckConstraint('weight_percentage BETWEEN 0 AND 100', name='ck_weight_pct_range'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'name', name='uq_persona_category_name')
    )
    op.create_index(op.f('ix_persona_categories_persona_id'), 'persona_categories', ['persona_id'], unique=False)
    op.create_table('persona_subcategories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_percentage', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', name='level_enum', native_enum=False), nullable=True),
    sa.CheckConstraint('weight_percentage BETWEEN 0 AND 100', name='ck_weight_pct_range'),
    sa.ForeignKeyConstraint(['category_id'], ['persona_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_persona_subcategory_name')
    )
    op.create_index(op.f('ix_persona_subcategories_category_id'), 'persona_subcategories', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_subcategories_category_id'), table_name='persona_subcategories')
    op.drop_table('persona_subcategories')
    op.drop_index(op.f('ix_persona_categories_persona_id'), table_name='persona_categories')
    op.drop_table('persona_categories')
    op.drop_index(op.f('ix_personas_job_description_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scores_persona_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('roles')
    op.drop_table('candidates')
    # ### end Alembic commands ###
