"""added_persona_warning_tables

Revision ID: 32cc9402c291
Revises: 760fc5b46ad2
Create Date: 2025-10-28 14:34:18.159688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cc9402c291'
down_revision: Union[str, None] = '760fc5b46ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_weight_warnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('below_min_message', sa.Text(), nullable=False),
    sa.Column('above_max_message', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'entity_type', 'entity_name', name='uq_persona_warning')
    )
    op.create_index('idx_entity_lookup', 'persona_weight_warnings', ['persona_id', 'entity_type', 'entity_name'], unique=False)
    op.create_index(op.f('ix_persona_weight_warnings_entity_name'), 'persona_weight_warnings', ['entity_name'], unique=False)
    op.create_index(op.f('ix_persona_weight_warnings_persona_id'), 'persona_weight_warnings', ['persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_weight_warnings_persona_id'), table_name='persona_weight_warnings')
    op.drop_index(op.f('ix_persona_weight_warnings_entity_name'), table_name='persona_weight_warnings')
    op.drop_index('idx_entity_lookup', table_name='persona_weight_warnings')
    op.drop_table('persona_weight_warnings')
    # ### end Alembic commands ###
