"""add_cv_text_column_to_candidate_cvs

Revision ID: b181357c3cf1
Revises: b2c3d4e5f6a7
Create Date: 2025-10-14 17:06:57.214567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b181357c3cf1'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_cvs', sa.Column('cv_text', sa.String(), nullable=True))
    op.drop_index('ix_job_descriptions_role_id', table_name='job_descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_descriptions_role_id', 'job_descriptions', ['role_id'], unique=False)
    op.drop_column('candidate_cvs', 'cv_text')
    # ### end Alembic commands ###
