"""added indices on job descriptions

Revision ID: b62a6078c98b
Revises: 097dd0d32372
Create Date: 2025-12-15 16:07:41.389225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62a6078c98b'
down_revision: Union[str, None] = '097dd0d32372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_job_descriptions_created_at')
        batch_op.drop_index('ix_job_descriptions_role_id')
        batch_op.create_index('idx_jd_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_jd_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_jd_role_id', ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_jd_role_id')
        batch_op.drop_index('idx_jd_created_by')
        batch_op.drop_index('idx_jd_created_at')
        batch_op.create_index('ix_job_descriptions_role_id', ['role_id'], unique=False)
        batch_op.create_index('ix_job_descriptions_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
