"""added_role_id_to_persona_model

Revision ID: d8ae1b634e84
Revises: 32cc9402c291
Create Date: 2025-10-29 09:50:53.680226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ae1b634e84'
down_revision: Union[str, None] = '32cc9402c291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('role_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'role_id')
    # ### end Alembic commands ###
