"""Persona Data Modeling

Revision ID: df1a9faecb7e
Revises: 
Create Date: 2025-10-06 17:22:44.453768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'df1a9faecb7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=False),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('cv_path', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('scores', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_percentage', sa.Integer(), nullable=False),
    sa.Column('range_min', sa.Float(), nullable=True),
    sa.Column('range_max', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('notes_id', sa.String(), nullable=True),
    sa.CheckConstraint('range_min <= range_max', name='ck_range_min_max'),
    sa.CheckConstraint('weight_percentage BETWEEN 0 AND 100', name='ck_weight_pct_range'),
    sa.ForeignKeyConstraint(['notes_id'], ['persona_notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'name', name='uq_persona_category_name')
    )
    op.create_index(op.f('ix_persona_categories_persona_id'), 'persona_categories', ['persona_id'], unique=False)
    op.create_table('persona_levels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['persona_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_notes_category_id'), 'persona_notes', ['category_id'], unique=False)
    op.create_index(op.f('ix_persona_notes_persona_id'), 'persona_notes', ['persona_id'], unique=False)
    op.create_table('persona_skillsets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('persona_category_id', sa.String(), nullable=True),
    sa.Column('persona_subcategory_id', sa.String(), nullable=True),
    sa.Column('technologies', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['persona_category_id'], ['persona_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_subcategory_id'], ['persona_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_skillsets_persona_category_id'), 'persona_skillsets', ['persona_category_id'], unique=False)
    op.create_index(op.f('ix_persona_skillsets_persona_id'), 'persona_skillsets', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_skillsets_persona_subcategory_id'), 'persona_skillsets', ['persona_subcategory_id'], unique=False)
    op.create_table('persona_subcategories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_percentage', sa.Integer(), nullable=False),
    sa.Column('range_min', sa.Float(), nullable=True),
    sa.Column('range_max', sa.Float(), nullable=True),
    sa.Column('level_id', sa.String(), nullable=True),
    sa.Column('skillset_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.CheckConstraint('range_min <= range_max', name='ck_range_min_max'),
    sa.CheckConstraint('weight_percentage BETWEEN 0 AND 100', name='ck_weight_pct_range'),
    sa.ForeignKeyConstraint(['category_id'], ['persona_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['persona_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skillset_id'], ['persona_skillsets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_persona_subcategory_name')
    )
    op.create_index(op.f('ix_persona_subcategories_category_id'), 'persona_subcategories', ['category_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scores_persona_id'), 'scores', ['persona_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('twitter_link', sa.String(), nullable=True),
    sa.Column('instagram_link', sa.String(), nullable=True),
    sa.Column('facebook_link', sa.String(), nullable=True),
    sa.Column('about_company', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('job_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_roles_name'), 'job_roles', ['name'], unique=True)
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('refined_text', sa.Text(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('original_document_filename', sa.String(), nullable=True),
    sa.Column('original_document_size', sa.String(), nullable=True),
    sa.Column('original_document_extension', sa.String(), nullable=True),
    sa.Column('document_word_count', sa.String(), nullable=True),
    sa.Column('document_character_count', sa.String(), nullable=True),
    sa.Column('selected_version', sa.String(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('selected_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['job_roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_description_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('weights', sqlite.JSON(), nullable=True),
    sa.Column('intervals', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_job_description_id'), 'personas', ['job_description_id'], unique=False)
    op.create_table('persona_change_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_change_logs_persona_id'), 'persona_change_logs', ['persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_change_logs_persona_id'), table_name='persona_change_logs')
    op.drop_table('persona_change_logs')
    op.drop_index(op.f('ix_personas_job_description_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_job_roles_name'), table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scores_persona_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('roles')
    op.drop_index(op.f('ix_persona_subcategories_category_id'), table_name='persona_subcategories')
    op.drop_table('persona_subcategories')
    op.drop_index(op.f('ix_persona_skillsets_persona_subcategory_id'), table_name='persona_skillsets')
    op.drop_index(op.f('ix_persona_skillsets_persona_id'), table_name='persona_skillsets')
    op.drop_index(op.f('ix_persona_skillsets_persona_category_id'), table_name='persona_skillsets')
    op.drop_table('persona_skillsets')
    op.drop_index(op.f('ix_persona_notes_persona_id'), table_name='persona_notes')
    op.drop_index(op.f('ix_persona_notes_category_id'), table_name='persona_notes')
    op.drop_table('persona_notes')
    op.drop_table('persona_levels')
    op.drop_index(op.f('ix_persona_categories_persona_id'), table_name='persona_categories')
    op.drop_table('persona_categories')
    op.drop_table('candidates')
    # ### end Alembic commands ###
