"""add_linkedin_link_to_companies

Revision ID: e54a12b7b2ff
Revises: b181357c3cf1
Create Date: 2025-10-15 16:14:35.845346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54a12b7b2ff'
down_revision: Union[str, None] = 'b181357c3cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('linkedin_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'linkedin_link')
    # ### end Alembic commands ###
