"""added_persona_notes_to_persona

Revision ID: ee1b28c20928
Revises: d8ae1b634e84
Create Date: 2025-10-29 11:59:59.245161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1b28c20928'
down_revision: Union[str, None] = 'd8ae1b634e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('persona_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'persona_notes')
    # ### end Alembic commands ###
